### ISSUE TITLE
test_reloc rewriter mode is failing on x86-64, Red Hat 7.3.1-2, with libc-2.25

### ISSUE THREAD

**Issue by mxz297** [dyninst/testsuite#49]

**Comment by hainest** [comment]
This is also consistently failing on cayenne.cs.wisc.edu, but not any other x86 platform I test on.

https://bottle.cs.wisc.edu/results/FAILED/477

**Comment by hainest** [comment]
Possibly fixed by https://github.com/dyninst/dyninst/issues/714?

**Comment by mxz297** [comment]
I believe I reported this on mic.cs.rice.edu, but now mic.cs.rice.edu has Fedora 26 instead of Red hat 7. It still has libc-2.25. 

I will run test suite on it.

**Comment by mxz297** [comment]
@hainest The rewriter failure on mic.cs.rice.edu still exists for both master and with my potential fix for gpu.cs.rice.edu.

Actually, I investigated this failure before and here I post my conversation with Ben Woodard:

Hi Ben,

Recently we encountered a dyninst test suite failure on a rhel7 x86 machine:

[xmeng@mic binaries]$
./rewritten_test_reloc.dyn_gcc_64_none_none_26423467 -test test_reloc
./rewritten_test_reloc.dyn_gcc_64_none_none_26423467: Relink
`/lib64/libdl.so.2' with `./libc.so.6' for IFUNC symbol `strcpy'
Segmentation fault (core dumped)

Google search shows that you have encountered a similar problem before
in this thread (https://bugzilla.redhat.com/show_bug.cgi?id=1500128).

In our test, we are rewriting libc.so. The test itself also uses
libpthread.so, which has the "NODELETE" attribute flag. Note that in
this case, libpthread.so is not instrumented. Neither the original
libc nor the rewritten libc has "NODELETE" flag. And if I just delete
our instrumented libc.so and use the original libc, the test runs
fine. So, it must be something that Dyninst does to the libc,
compounded with this "NODELETE" bug, leads to the test crash.

From the bugzilla discussion, we couldn't tell what is the root
problem. Any suggestions?

Thanks,

--Xiaozhu

Ben replied:

You might find more information here:
https://sourceware.org/bugzilla/show_bug.cgi?id=20839 which is the upstream version of the bug. The problem is unlikely to get fixed in RHEL7 because the problem isn’t fixed upstream yet. As you can see someone just posted a patch earlier today. It hasn’t been reviewed and committed. However, this isn’t the first time that someone has posted a patch. Other attempts to fix the problem had some unacceptable side effects and were not committed. We won’t consider backporting the patch until it is accepted upstream and by the time that works through the process, we’re kind of done with RHEL7 except for critical problems.

The way that this bug manifests is when there is library which has NODELETE has been loaded but subsequently there is some kind of failure loading a library and so the whole dependency change should be unloaded. However because of the NODELETE that lib wasn’t unloaded leaving it in an incompletely relocated state. After thinking through it carefully it seems to be agreed that NODELETE shouldn’t take effect until after the full dependency chain is loaded and relocated.

I suspect that the problem that you are running into is some sort of failure and the incompletely relocated libpthread.

Does that help?

-ben


I don't think I then figured out how to make it passing.

**Comment by hainest** [comment]
I'm seeing test_reloc failures on [coriander](https://bottle.cs.wisc.edu/results/CRASHED/526) and [cayenne](https://bottle.cs.wisc.edu/results/FAILED/538). I would suggest we focus on those machines since they are part of our default testbed, then see if any fixes that come from them might work on mic.cs.rice.edu. Does that work for you?

**Comment by mxz297** [comment]
> I'm seeing test_reloc failures on [coriander](https://bottle.cs.wisc.edu/results/CRASHED/526) and [cayenne](https://bottle.cs.wisc.edu/results/FAILED/538). I would suggest we focus on those machines since they are part of our default testbed, then see if any fixes that come from them might work on mic.cs.rice.edu. Does that work for you?

Yes, I don't think we can ever fix test_reloc on mic.cs.rice.edu. For coriander, I think it is more of the problem of handling libc-2.29.so. So, I will start with cayenne.

**Comment by hainest** [comment]
Sounds good. cayenne is my office machine, and it's two cores are too wimpy to build dyninst and let me work. I have a version built with the test_reloc fix in /nobackup/thaines/paradyn/m1w0JeBt that you are welcome to use.

**Comment by mxz297** [comment]
> Sounds good. cayenne is my office machine, and it's two cores are too wimpy to build dyninst and let me work. I have a version built with the test_reloc fix in /nobackup/thaines/paradyn/m1w0JeBt that you are welcome to use.

I saw:

```
[xmeng@cayenne] (13)$ ls -al /nobackup/thaines/paradyn/m1w0JeBt
ls: cannot open directory '/nobackup/thaines/paradyn/m1w0JeBt': Permission denied
```

**Comment by hainest** [comment]
Oh, sorry, I forgot to update the permissions. I changed the group to 'paradyn', so you should be able to see it now.

**Comment by mxz297** [comment]
> Oh, sorry, I forgot to update the permissions. I changed the group to 'paradyn', so you should be able to see it now.

Getting closer. Now I can get to `/nobackup/thaines/paradyn`. I still cannot get into that directory because the group permission is not set:

```
drwx------  4 thaines paradyn   4096 Mar  9 21:17 m1w0JeBt/
```

**Comment by hainest** [comment]
That's weird. I used chgrp -R. I re-ran it as root. If that doesn't work, then just go ahead and build dyninst in your directory. I'll go grab a snack.

**Comment by mxz297** [comment]
As usual, when I ran it, it passes:

```
[xmeng@cayenne] (118)$ ./runTests -test test_reloc -rewriter -all -64
test_reloc                 g++    none 64  rewriter NA      dynamic nonPIC  PASSED
test_reloc                 g++    none 64  rewriter NA      dynamic PIC     PASSED
test_reloc                 gcc    none 64  rewriter NA      dynamic nonPIC  PASSED
test_reloc                 gcc    none 64  rewriter NA      dynamic PIC     PASSED
```

This is on cayenne. My dyninst is at:

```
commit c20f39b8e5428a94d3a61f6f60cab9b5402154eb (HEAD -> test_reloc_fix, origin/test_reloc_fix)
Author: Xiaozhu Meng <mxz297@gmail.com>
Date:   Sun Mar 1 20:16:08 2020 -0600

    Fix jump table finalization
```

The testsuite is at:

```
commit 45587884dc88ad541b995eea34ed6d00ececc1f6 (HEAD -> master, origin/master, origin/HEAD)
Author: Tim Haines <thaines.astro@gmail.com>
Date:   Mon Mar 9 17:54:02 2020 -0500

    Reduce watchdog timeout to ten minutes (#144)
```

**Comment by hainest** [comment]
But of course! Is test_reloc_fix rebased on the current head of dyninst/master?

**Comment by mxz297** [comment]
Not yet. I will rebase and rerun it.

**Comment by mxz297** [comment]
Good or bad news. After rebasing:

```
[xmeng@cayenne] (165)$ ./runTests -test test_reloc -rewriter -all -64
test_reloc                 g++    none 64  rewriter NA      dynamic nonPIC  PASSED
test_reloc                 g++    none 64  rewriter NA      dynamic PIC     PASSED
test_reloc                 gcc    none 64  rewriter NA      dynamic nonPIC  PASSED
test_reloc                 gcc    none 64  rewriter NA      dynamic PIC     FAILED (Group Teardown)
```

Do you know whether master fails or not?

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?hostname=cayenne&since_date=2020-03-01

it does (see run 531).

**Comment by mxz297** [comment]
Then it looks to me that some recent merged PR caused the problem. It looks to me that you did not get a chance to run the tests for https://github.com/dyninst/dyninst/pull/698?

**Comment by hainest** [comment]
Yeah, Sasha merged that before running on all platforms. I'm running HEAD^ on zeroah now for comparison. If there are substantial differences, I'll have him jump back to debugging that.
